services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: crocssa
      POSTGRES_USER: crocssa
      POSTGRES_PASSWORD: crocssa
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: [crocssa]

  backend:
    build: ./backend
    command: flask --app run run --host 0.0.0.0 --reload
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://crocssa:crocssa@db:5432/crocssa
      SECRET_KEY: dev
    volumes:
      - ./backend:/app
      - uploads:/app/uploads
    ports: ["5000:5000"]
    depends_on: [db]
    networks: [crocssa]

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app                 # źródła ↔ hot-reload
      - frontend_node_modules:/app/node_modules
    ports: ["5173:5173"]
    depends_on: [backend]
    networks: [crocssa]

volumes:
  db-data:
  frontend_node_modules:
  uploads:

networks:
  crocssa:
